# Default values for mongodb-tech-adapter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Docker Registry Secret name used to access a private repo
dockerRegistrySecretName: regcred

image:
  # -- Image repository
  registry: registry.gitlab.com/agilefactory/witboost.mesh/provisioning/witboost.mesh.provisioning.mongodb
  # -- Image tag
  tag: latest
  # -- The imagePullPolicy for a container and the tag of the image affect when the kubelet attempts to pull (download) the specified image.
  pullPolicy: Always

# -- define extra variables to add to the container(s)
# e.g:
# extraEnvVars:
#   - name: FOO
#     value: "10"
extraEnvVars:
  - name: CONNECTION_STRING
    valueFrom:
      secretKeyRef:
        name: mongodb-addons-secrets
        key: CONNECTION_STRING
  - name: USERS_DATABASE
    value: ""
  - name: DEVELOPER_ROLES
    value: []
  - name: CONSUMER_ACTIONS
    value: []
  - name: USECASETEMPLATEID
    value: "urn:dmb:utm:mongodb-outputport-template:0.0.0"
  - name: USECASETEMPLATESUBID
    value: "urn:dmb:utm:mongodb-outputport-subcomponent-template:0.0.0"

# -- readiness probe spec
readinessProbe: {}

# -- liveness probe spec
livenessProbe: {}

# -- security context spec
securityContext:
  runAsUser: 1001
  allowPrivilegeEscalation: false
  runAsNonRoot: true

# -- resources spec
resources: {}

# -- Allows you to specify common labels
labels: {}

